add_executable(rgbt_common_tests common/version_test.cpp)

target_link_libraries(rgbt_common_tests PRIVATE rgbt_common GTest::gtest_main)

rgbt_set_project_warnings(rgbt_common_tests)
rgbt_apply_sanitizer(rgbt_common_tests)
rgbt_apply_sanitizer(rgbt_common)

include(GoogleTest)
gtest_discover_tests(rgbt_common_tests)
